spring.application.name=empresa-de-telefonia


# Base de datos en la nube
spring.datasource.url=jdbc:mysql://root:LFrFVVAFBMUHafWmukMoMTUcqrcOPFzq@zephyr.proxy.rlwy.net:14759/railway
spring.datasource.username=root
spring.datasource.password=LFrFVVAFBMUHafWmukMoMTUcqrcOPFzq

# Propiedades de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
