spring.application.name=empresa-de-telefonia


# Base de datos en la nube
spring.datasource.url=jdbc:mysql://root:wvIyrwjwlIdUuYLmBdfssuedvmqfiMkI@zephyr.proxy.rlwy.net:17048/railway
spring.datasource.username=root
spring.datasource.password=wvIyrwjwlIdUuYLmBdfssuedvmqfiMkI

# Propiedades de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
